#########################################################################
#  _____  _                       _                             _       #
# |  __ \(_)                     | |                           | |      #
# | |  | |_ ___  ___ ___  _ __ __| |         __ _  __ _ _ __ __| | __ _ #
# | |  | | / __|/ __/ _ \| '__/ _` |        / _` |/ _` | '__/ _` |/ _` |#
# | |__| | \__ \ (_| (_) | | | (_| |       | (_| | (_| | | | (_| | (_| |#
# |_____/|_|___/\___\___/|_|  \__,_|        \__,_|\__,_|_|  \__,_|\__,_|#
#                                       ______                          #
#                                      |______|                         #
#########################################################################
bot:
  # Discord botunuzun tokeni
  token: 'MTE2NjM2NTYwNDA5ODM0MzAyMg.GDQZA3.IaYppnaT0rZEAoqTo_4byjbNCR77Afji2VdRfM'
  # Discord botunuzun application idsi
  id: '1166365604098343022'
  # Discord botunun durum kÄ±smÄ±
  status:
    # Discord botunun aÃ§Ä±klma kÄ±smÄ±ndaki event; playing = Oynuyor, streaming = YayÄ±nda, listening = Dinliyor, watching = Ä°zliyor, competing = YarÄ±ÅŸmada yarÄ±ÅŸÄ±yor.
    activity: 'streaming'
    # Discord botunun aÃ§Ä±klama yazÄ±sÄ±; %onDutyPolice% yazarak aktif mesaideki memurlarÄ±n sayÄ±sÄ±nÄ± gÃ¶sterebilirsiniz.
    text: '%onDutyPolice% KiÅŸi Mesaide! - Newadors YÃ¶netiyor!'
    # Discord botunun aÃ§Ä±klma kÄ±smÄ±ndaki event streaming olarak ayarlanÄ±rsa aÅŸaÄŸÄ±daki twitch kÄ±smÄ±nÄ± doldurunuz.
    twitch: 'https://www.twitch.tv/example'
    # Discord botunun aktiflik kÄ±smÄ±; online = Aktif, idle = BoÅŸta, dnd = RahatsÄ±z Etmeyin, invisible = Ã‡evrimdÄ±ÅŸÄ±.
    status: 'idle'
guild:
  # Discord sunucunuzun idsi
  id: '1164158876116058242'
settings:
  departmentName: 'San Andreas State Department'
  departmentLogo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/U.S._Department_of_State_official_seal.svg/2048px-U.S._Department_of_State_official_seal.svg.png'
  departmentBanner: 'https://cdn.discordapp.com/attachments/1164158877529542737/1170095875498983565/state.png?ex=6557cbb4&is=654556b4&hm=cf89021ff37a9679bf15f5141b938d8e7e08140ce7632ba3f8aab2e0f5c966fa&'
  departmentColor: '#0000ff'
  roles:
    # RÃ¼tbe rollerinin idleri
    officers: ['1164158876451610689', '']
  channels:
    # Log kanalÄ±nÄ±n idsi
    log: '1164158877529542737'
  # Mesaj iÃ§erikelrinde kulanÄ±lan emojiler, ğŸ“‹ ÅŸeklinde, :emojiAdÄ±: ÅŸeklinde veya idsiyle kullanÄ±labilir.
  emojis:
    department: 'ğŸ‘®'
    on: 'ğŸŸ©'
    off: 'ğŸŸ¥'
    warning: 'âš ï¸'
    info: 'ğŸ“‹'
    clock: 'â²ï¸'
commands:
    # Aktif mesaideki Ã¼yeleri gÃ¶steren komut
    activeDuty:
      # Bu komutu kullanabilmek iÃ§in gereken rol
      requiredRole: '1164158876451610689'
